import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(anim, [])



  return (
    <>
      <Head>
        <title>Metier des mathématiques</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='hero' >
        <img src="assets/img/image-hero.png" />
        <h1>
          CHERCHEUR EN PERFORMANCES SPORTIVES
        </h1>

      </section>
      <section className='intro' >


        <p>
          Les mathématiques sont présentes dans de nombreux domaines, y compris le sport. En effet, les professionnels du sport ont souvent besoin de mathématiques pour rechercher la performance. Les sportifs de haut niveau ont accès à un grand nombre de données et ont donc besoin d'un spécialiste en statistiques pour les comprendre et les exploiter.Les résultats obtenus peuvent conduire à de nouvelles méthodes d'entraînement, par exemple. Les mathématiques peuvent également aider à anticiper d'éventuelles blessures ou aider un entraîneur à décider entre deux joueurs pour un match. La recherche en performance sportive va même jusqu'à développer des outils pour prédire les événements d'un match en particulier. Aujourd'hui, dans des sports comme le football ou le rugby, toutes les clubs utilisent les mathématiques pour identifier les points forts/faibles de leurs adversaires ou de leur propre équipe.        </p>
        <img src="assets/img/image-1.png" />
      </section>

      <section className='trigger'></section>

      <section className='scene'>
        <canvas id='hero' />
        <h2>
          CURSUS ET QUALITES NECESSAIRES
        </h2>
        <div >
          <p>
            Pour accéder a un poste dans le sport un bac +5 est souvent nécessaire et une bonne maitrise des statistiques et de l’informatique. Le master Statistique et Science des Données a l’université de Montpellier est très adapté par exemple.          </p>
          <p>
            Un chercheur en performance sportive a besoin de ces qualités:<br /><br />
            Capacité à travailler en équipe<br /><br />
            Curiosité et créativité<br /><br />
            Capacité à communiquer efficacement<br /><br />
            Persévérance         </p>
        </div>
      </section>

      <section className='job-options'>
        <div >

          <img id='i1' src="assets/img/image 7.png" />
          <img id='i2' src="assets/img/image 8.png" />
          <img id='i3' src="assets/img/image 9.png" />
        </div>
        <p>
          Les chercheurs en performance sportive peuvent travailler dans une variété d'organisations:<br /><br />
          Que ça soit dans la recherche pure, comme enseignant-chercheur (CNRS, INSERM, INRP, etc.).<br /><br />
          Au sein de Clubs et de Fédérations Sportives.<br /><br />
          Au sein des Collectivités Territoriales ou du Ministère de La Jeunesse et des Sports, pour intervenir dans la politique sportive. (service culturel d’une grande Mairie, etc.).<br /><br />
          Comme éducateur sportif (après un deuxième diplôme à acquérir par voie professionnelle dans le secteur du social).<br /><br />
          Comme délégué médical au sein de laboratoires.<br /><br />
          Comme diététicien après la validation d’un deuxième diplôme en règle générale.<br /><br />
          Les postes sont diverses et variés permettant à un chercheur en performance sportive de réorienté professionnellement au cours de sa carrière.<br /><br />
        </p>

      </section >
      <section className='impact' >
        <div>
          <h2>
            IMPACT
          </h2>

          <p>
            Comme illustré dans “Le Stratège”, le rôle de chercheur en performances sportive à eu un impact majeur dans le monde de l’industrie du sport.<br /><br />
            Tiré d'une histoire vraie, le film "Le Stratège" suit une équipe moyenne de baseball aux États-Unis qui va complètement changer sa stratégie de recrutement en choisissant ses joueurs uniquement sur des critères statistiques. Cette stratégie a connu un grand succès car l'équipe en question a remporté la ligue de baseball cette année-là. Cette histoire a révolutionné complètement le baseball et le sport en général, car dans les années qui ont suivi, les anciennes méthodes de recrutement ont été abandonnées au profit d'un recrutement plus rationnel et basé sur les statistiques dans de nombreux clubs. En France, par exemple, le Toulouse Football Club utilise uniquement les statistiques pour recruter ses joueurs. Cette stratégie s'appelle maintenant le "Moneyball" et est utilisée partout à des niveaux différents.        </p>
        </div>

        <img src="assets/img/image 10.png" />
      </section>
    
    </>
  )
}


const anim = () => {

  gsap.registerPlugin(ScrollTrigger);
  let ctx = gsap.context(() => {
    console.clear();

    const canvas = document.getElementById("hero");
    const context = canvas.getContext("2d");

    canvas.width = 1158;
    canvas.height = 770;

    const frameCount = 92;
    const currentFrame = index => `/api/images/${index}`

    const images = []
    const toDraw = {
      frame: 0
    };

    for (let i = 1; i < frameCount + 1; i++) {
      const img = new Image();
      img.src = currentFrame(i);
      img.onload = () => {
        return 0
      };
      images.push(img);

    }


    const tl = gsap.timeline({ repeat: 0, repeatDelay: 0.5, yoyo: false, yoyoEase: true, ease: "none" })




    gsap.to(toDraw, {
      frame: frameCount - 1,
      snap: "frame",

      ease: "none",
      scrollTrigger: {
        trigger: ".trigger",
        start: "top top",
        end: "+=50vh",
        scrub: true,
      },
      onUpdate: render // use animation onUpdate instead of scrollTrigger's onUpdate
    });

    tl.to(
      '#i1',
      {
        scrollTrigger: {
          trigger: '#i1',
          start: "top 80%",
          end: "bottom 50%",
          scrub: 1,


        },
        x: 0,
        y: 0,
        scale: 1,
        opacity: 1,
        duration: 0.5,
        ease: "easeinOut",

      }

    )
    tl.to(
      '#i2',
      {
        scrollTrigger: {
          trigger: '#i2',
          start: "top 80%",
          end: "bottom 50%",
          scrub: 1,
        },
        x: 0,
        y: 0,
        scale: 1,
        opacity: 1,
        duration: 0.5,
        ease: "easeinOut",

      }

    )
    tl.to(
      '#i3',
      {
        scrollTrigger: {
          trigger: '#i3',
          start: "top 80%",
          end: "bottom 50%",
          scrub: 1,
        },
        x: 0,
        y: 0,
        scale: 1,
        opacity: 1,
        duration: 0.5,
        ease: "easeinOut",

      }

    )




    images[0].onload = render;


    function render() {
      const image = images[toDraw.frame]
      //context.clearRect(0, 0, canvas.width, canvas.height);
      context.drawImage(image, canvas.width / 2 - image.width / 2,
        canvas.height / 2 - image.height / 2);

    }







    return () => ctx.revert();


  })


}