import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() => {

    gsap.registerPlugin(ScrollTrigger);
    let ctx = gsap.context(() => {
      console.clear();

      const canvas = document.getElementById("hero");
      const context = canvas.getContext("2d");

      canvas.width = 1158;
      canvas.height = 770;

      const frameCount = 92;
      const currentFrame = index => `/api/images/${index}`

      const images = []
      const airpods = {
        frame: 0
      };

      for (let i = 1; i < frameCount + 1; i++) {
        const img = new Image();
        img.src = currentFrame(i);
        img.onload = () => { 
          return 0
        };
        images.push(img);

      }

      gsap.to(airpods, {
        frame: frameCount - 1,
        snap: "frame",
        ease: "none",
        scrollTrigger: {
          scrub: 0.5
        },
        onUpdate: render // use animation onUpdate instead of scrollTrigger's onUpdate
      });

      images[0].onload = render;


      function render() {

        context.clearRect(0, 0, canvas.width, canvas.height);
        context.drawImage(images[airpods.frame], 0, 0);

      }







      return () => ctx.revert();


    })


  }, [])



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <canvas id='hero' />


    </>
  )
}
